spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/messages_db
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
    format_sql: true
#    security:
#      enabled: true